# -*- coding: utf-8 -*-
"""
CSS emitters. Every value comes from the derived token set; nothing is typed
by hand into a stylesheet.

Zero JavaScript. Components that would ordinarily need it are built on native
HTML elements (<details>, <dialog>) or CSS state selectors. Components that
genuinely cannot work without JS are documented as such and not faked.
"""

from .derive import real_keys


def _fluid(min_px, max_px, vmin, vmax):
    """A clamp() that scales linearly between two viewport widths."""
    slope = (max_px - min_px) / (vmax - vmin)
    intercept = min_px - slope * vmin
    return (f"clamp({min_px/16:.4f}rem, {intercept/16:.4f}rem + "
            f"{slope*100:.4f}vw, {max_px/16:.4f}rem)")


def type_scale(tok):
    ts = tok["type_scale"]
    ratio, base = ts["ratio"], ts["base_px"]
    vmin, vmax = ts["fluid_viewport_min_px"], ts["fluid_viewport_max_px"]
    out = []
    for name, step in real_keys(ts["steps"]).items():
        max_px = base * (ratio ** step)
        # Larger steps compress more on small screens; body text does not shrink.
        shrink = 1.0 if step <= 0 else max(0.62, 1.0 - 0.075 * step)
        min_px = max_px * shrink
        out.append((name, min_px, max_px, _fluid(min_px, max_px, vmin, vmax)))
    return out


def emit_tokens(tok, col):
    L = []
    a = L.append
    a("/* Generated by the WDS from tokens.json + the canonical palette.")
    a("   Do not edit. Run build_wds.py. */")
    a("")

    def block(selector, theme, indent="  "):
        a(f"{selector} {{")
        a(f"{indent}color-scheme: {theme};")
        for k, v in col[theme].items():
            a(f"{indent}--wds-{k}: {v};")
        a("}")
        a("")

    # Dark is the default: the site is dark-first.
    a(":root {")
    a("  color-scheme: dark;")
    for k, v in col["dark"].items():
        a(f"  --wds-{k}: {v};")

    # ---- typography ------------------------------------------------------
    a("")
    a("  --wds-font-sans: -apple-system, BlinkMacSystemFont, 'Segoe UI', "
      "Roboto, Helvetica, Arial, sans-serif;")
    a("  --wds-font-mono: ui-monospace, 'SF Mono', 'Cascadia Code', Consolas, "
      "'Liberation Mono', monospace;")
    for name, mn, mx, clamp in type_scale(tok):
        a(f"  --wds-text-{name}: {clamp};")
    a("  --wds-leading-tight: 1.15;")
    a("  --wds-leading-snug: 1.35;")
    a("  --wds-leading-normal: 1.6;")
    a("  --wds-leading-relaxed: 1.75;")
    a("  --wds-tracking-tight: -0.02em;")
    a("  --wds-tracking-normal: 0;")
    a("  --wds-tracking-wide: 0.08em;")
    a("  --wds-tracking-caps: 0.14em;")
    a("  --wds-weight-light: 300;")
    a("  --wds-weight-regular: 400;")
    a("  --wds-weight-medium: 500;")
    a("  --wds-weight-semibold: 600;")

    # ---- spacing ---------------------------------------------------------
    a("")
    unit = tok["spacing"]["unit_px"]
    for s in tok["spacing"]["steps"]:
        a(f"  --wds-space-{s}: {s*unit/16:.4f}rem;")

    # ---- radius, borders -------------------------------------------------
    a("")
    for k, v in tok["radius"].items():
        a(f"  --wds-radius-{k}: {v}px;")
    for k, v in tok["border_width"].items():
        a(f"  --wds-border-{k}: {v}px;")

    # ---- grid ------------------------------------------------------------
    a("")
    g = tok["grid"]
    a(f"  --wds-container: {g['container_max_px']/16:.4f}rem;")
    a(f"  --wds-reading: {g['reading_max_ch']}ch;")
    a(f"  --wds-code-width: {g['code_max_ch']}ch;")
    a(f"  --wds-gallery: {g['gallery_max_px']/16:.4f}rem;")
    a(f"  --wds-hero: {g['hero_max_px']/16:.4f}rem;")
    a(f"  --wds-columns: {g['columns']};")
    a(f"  --wds-gutter: var(--wds-space-{g['gutter_step']});")
    a(f"  --wds-margin: var(--wds-space-{g['margin_step']});")

    # ---- motion ----------------------------------------------------------
    a("")
    for k, v in real_keys(tok["motion"]["duration_ms"]).items():
        a(f"  --wds-duration-{k}: {v}ms;")
    for k, v in tok["motion"]["easing"].items():
        a(f"  --wds-ease-{k}: {v};")

    # ---- z-index, opacity, blur -----------------------------------------
    a("")
    for k, v in tok["elevation"]["z_index"].items():
        a(f"  --wds-z-{k}: {v};")
    for k, v in tok["opacity"].items():
        a(f"  --wds-opacity-{k}: {v};")
    for k, v in tok["blur_px"].items():
        a(f"  --wds-blur-{k}: {v}px;")

    # ---- elevation: surface first, shadow second ------------------------
    a("")
    a("  --wds-shadow-raised: 0 1px 2px rgb(0 0 0 / 0.30);")
    a("  --wds-shadow-overlay: 0 4px 16px rgb(0 0 0 / 0.40);")
    a("  --wds-shadow-modal: 0 12px 48px rgb(0 0 0 / 0.55);")

    # ---- focus, targets --------------------------------------------------
    a("")
    a(f"  --wds-focus-width: {tok['focus']['ring_width_px']}px;")
    a(f"  --wds-focus-offset: {tok['focus']['ring_offset_px']}px;")
    a(f"  --wds-touch-target: {tok['touch_target_min_px']}px;")
    a("}")
    a("")

    # ---- light theme -----------------------------------------------------
    a("/* Light theme. Auto by preference, overridable by [data-theme]. */")
    a("@media (prefers-color-scheme: light) {")
    a("  :root:not([data-theme='dark']) {")
    a("    color-scheme: light;")
    for k, v in col["light"].items():
        a(f"    --wds-{k}: {v};")
    a("  }")
    a("}")
    a("")
    block(":root[data-theme='light']", "light", "  ")
    block(":root[data-theme='dark']", "dark", "  ")

    # ---- OLED ------------------------------------------------------------
    a("/* OLED: true black saves power and removes surface glow. Surfaces")
    a("   still separate, because the stack is lightness-based, not shadow. */")
    a(":root[data-theme='oled'] {")
    a("  color-scheme: dark;")
    for k, v in col["dark"].items():
        a(f"  --wds-{k}: {v};")
    a("  --wds-bg: #000000;")
    a("  --wds-surface: #0a0d11;")
    a("  --wds-surface-elevated: #12161b;")
    a("  --wds-shadow-raised: none;")
    a("  --wds-shadow-overlay: none;")
    a("  --wds-shadow-modal: none;")
    a("}")
    a("")

    # ---- forced colors ---------------------------------------------------
    a("/* Forced colours: hand every colour back to the operating system. */")
    a("@media (forced-colors: active) {")
    a("  :root {")
    a("    --wds-bg: Canvas;")
    a("    --wds-surface: Canvas;")
    a("    --wds-surface-elevated: Canvas;")
    a("    --wds-fg: CanvasText;")
    a("    --wds-fg-secondary: CanvasText;")
    a("    --wds-fg-tertiary: GrayText;")
    a("    --wds-fg-quiet: GrayText;")
    a("    --wds-accent: LinkText;")
    a("    --wds-border: CanvasText;")
    a("    --wds-border-strong: CanvasText;")
    a("    --wds-focus: Highlight;")
    a("  }")
    a("}")
    a("")

    # ---- reduced motion ---------------------------------------------------
    a("/* Reduced motion: durations collapse at the token level, so every")
    a("   component obeys without writing a single override. */")
    a("@media (prefers-reduced-motion: reduce) {")
    a("  :root {")
    for k in real_keys(tok["motion"]["duration_ms"]):
        a(f"    --wds-duration-{k}: 1ms;")
    a("  }")
    a("}")
    return "\n".join(L) + "\n"


def emit_base(tok):
    return """/* Generated by the WDS. Do not edit. */

*, *::before, *::after { box-sizing: border-box; }

html {
  -webkit-text-size-adjust: 100%;
  scrollbar-color: var(--wds-scrollbar-thumb) var(--wds-scrollbar-track);
}

body {
  margin: 0;
  background: var(--wds-bg);
  color: var(--wds-fg);
  font-family: var(--wds-font-sans);
  font-size: var(--wds-text-body);
  line-height: var(--wds-leading-normal);
  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
}

::selection { background: var(--wds-selection); color: var(--wds-fg); }

:focus-visible {
  outline: var(--wds-focus-width) solid var(--wds-focus);
  outline-offset: var(--wds-focus-offset);
  border-radius: var(--wds-radius-xs);
}
:focus:not(:focus-visible) { outline: none; }

h1, h2, h3, h4, h5, h6 {
  margin: 0 0 var(--wds-space-4);
  font-weight: var(--wds-weight-semibold);
  line-height: var(--wds-leading-tight);
  letter-spacing: var(--wds-tracking-tight);
  text-wrap: balance;
}
h1 { font-size: var(--wds-text-h1); }
h2 { font-size: var(--wds-text-h2); }
h3 { font-size: var(--wds-text-h3); }
h4 { font-size: var(--wds-text-h4); }
h5 { font-size: var(--wds-text-h5); letter-spacing: var(--wds-tracking-normal); }

p { margin: 0 0 var(--wds-space-4); max-width: var(--wds-reading); text-wrap: pretty; }
p:last-child { margin-bottom: 0; }

a {
  color: var(--wds-accent);
  text-decoration-thickness: 1px;
  text-underline-offset: 0.18em;
  transition: color var(--wds-duration-fast) var(--wds-ease-standard);
}
a:hover { color: var(--wds-accent-hover); }
a:active { color: var(--wds-accent-active); }

small, .wds-caption {
  font-size: var(--wds-text-caption);
  color: var(--wds-fg-tertiary);
}

code, kbd, samp, pre { font-family: var(--wds-font-mono); font-size: 0.9em; }

code {
  background: var(--wds-code-bg);
  border: var(--wds-border-hairline) solid var(--wds-border-subtle);
  border-radius: var(--wds-radius-sm);
  padding: 0.1em 0.35em;
}

hr {
  border: 0;
  border-top: var(--wds-border-hairline) solid var(--wds-border-subtle);
  margin: var(--wds-space-12) 0;
}

img, svg, video { max-width: 100%; height: auto; display: block; }

ul, ol { margin: 0 0 var(--wds-space-4); padding-left: var(--wds-space-6); }
li { margin-bottom: var(--wds-space-2); max-width: var(--wds-reading); }

blockquote {
  margin: var(--wds-space-6) 0;
  padding-left: var(--wds-space-5);
  border-left: var(--wds-border-medium) solid var(--wds-accent);
  color: var(--wds-fg-secondary);
}

/* Layout primitives */
.wds-container {
  max-width: var(--wds-container);
  margin-inline: auto;
  padding-inline: var(--wds-margin);
}
.wds-reading { max-width: var(--wds-reading); }
.wds-grid {
  display: grid;
  grid-template-columns: repeat(var(--wds-columns), minmax(0, 1fr));
  gap: var(--wds-gutter);
}
.wds-stack > * + * { margin-top: var(--wds-space-4); }
.wds-section { padding-block: var(--wds-space-16); }

@media (max-width: 719px) {
  .wds-grid { grid-template-columns: repeat(4, minmax(0, 1fr)); }
}
"""


def emit_components(tok):
    return """/* Generated by the WDS. Do not edit.
   Zero JavaScript: every component below is CSS or native HTML. */

/* ---------------------------------------------------------- buttons ---- */
.wds-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: var(--wds-space-2);
  min-height: var(--wds-touch-target);
  padding: var(--wds-space-3) var(--wds-space-5);
  border: var(--wds-border-thin) solid transparent;
  border-radius: var(--wds-radius-md);
  font: inherit;
  font-weight: var(--wds-weight-medium);
  line-height: 1;
  cursor: pointer;
  text-decoration: none;
  transition: background-color var(--wds-duration-fast) var(--wds-ease-standard),
              border-color var(--wds-duration-fast) var(--wds-ease-standard),
              color var(--wds-duration-fast) var(--wds-ease-standard);
}
.wds-btn--primary { background: var(--wds-accent); color: var(--wds-bg); }
.wds-btn--primary:hover { background: var(--wds-accent-hover); }
.wds-btn--primary:active { background: var(--wds-accent-active); }
.wds-btn--secondary {
  background: var(--wds-surface-interactive);
  color: var(--wds-fg);
  border-color: var(--wds-border);
}
.wds-btn--secondary:hover { border-color: var(--wds-border-strong); }
.wds-btn--ghost { background: transparent; color: var(--wds-fg-secondary); }
.wds-btn--ghost:hover {
  background: var(--wds-surface);
  color: var(--wds-fg);
}
.wds-btn--danger { background: var(--wds-danger); color: var(--wds-bg); }
.wds-btn[disabled], .wds-btn[aria-disabled='true'] {
  opacity: var(--wds-opacity-disabled);
  cursor: not-allowed;
}
.wds-btn--sm { min-height: 32px; padding: var(--wds-space-2) var(--wds-space-3); }

/* ------------------------------------------------------------ badges --- */
.wds-badge {
  display: inline-flex;
  align-items: center;
  gap: var(--wds-space-1);
  padding: var(--wds-space-1) var(--wds-space-2);
  border-radius: var(--wds-radius-sm);
  font-family: var(--wds-font-mono);
  font-size: var(--wds-text-caption);
  letter-spacing: var(--wds-tracking-wide);
  background: var(--wds-surface);
  color: var(--wds-fg-secondary);
  border: var(--wds-border-hairline) solid var(--wds-border-subtle);
}
.wds-badge--success { background: var(--wds-success-surface); color: var(--wds-success); border-color: var(--wds-success); }
.wds-badge--warning { background: var(--wds-warning-surface); color: var(--wds-warning); border-color: var(--wds-warning); }
.wds-badge--danger  { background: var(--wds-danger-surface);  color: var(--wds-danger);  border-color: var(--wds-danger); }
.wds-badge--info    { background: var(--wds-info-surface);    color: var(--wds-info);    border-color: var(--wds-info); }

.wds-tag {
  display: inline-block;
  padding: var(--wds-space-1) var(--wds-space-3);
  border-radius: var(--wds-radius-pill);
  background: var(--wds-surface);
  border: var(--wds-border-hairline) solid var(--wds-border-subtle);
  font-size: var(--wds-text-caption);
  color: var(--wds-fg-secondary);
}

/* ------------------------------------------------------------- cards --- */
.wds-card {
  background: var(--wds-surface);
  border: var(--wds-border-hairline) solid var(--wds-border-subtle);
  border-radius: var(--wds-radius-lg);
  padding: var(--wds-space-6);
}
.wds-card--interactive {
  transition: border-color var(--wds-duration-base) var(--wds-ease-standard),
              background-color var(--wds-duration-base) var(--wds-ease-standard);
}
.wds-card--interactive:hover {
  border-color: var(--wds-border-strong);
  background: var(--wds-surface-elevated);
}
.wds-card__title { font-size: var(--wds-text-h4); margin-bottom: var(--wds-space-2); }
.wds-card__meta {
  font-family: var(--wds-font-mono);
  font-size: var(--wds-text-caption);
  color: var(--wds-fg-tertiary);
  letter-spacing: var(--wds-tracking-wide);
}

/* ---------------------------------------------------------- callouts --- */
.wds-callout {
  display: grid;
  grid-template-columns: auto 1fr;
  gap: var(--wds-space-3);
  padding: var(--wds-space-4) var(--wds-space-5);
  border-radius: var(--wds-radius-md);
  border-left: var(--wds-border-thick) solid var(--wds-border-strong);
  background: var(--wds-surface);
}
.wds-callout--info    { border-left-color: var(--wds-info);    background: var(--wds-info-surface); }
.wds-callout--success { border-left-color: var(--wds-success); background: var(--wds-success-surface); }
.wds-callout--warning { border-left-color: var(--wds-warning); background: var(--wds-warning-surface); }
.wds-callout--danger  { border-left-color: var(--wds-danger);  background: var(--wds-danger-surface); }
.wds-callout__label {
  font-family: var(--wds-font-mono);
  font-size: var(--wds-text-caption);
  letter-spacing: var(--wds-tracking-caps);
  text-transform: uppercase;
  color: var(--wds-fg-tertiary);
}

/* ------------------------------------------------------------ header --- */
.wds-header {
  position: sticky;
  top: 0;
  z-index: var(--wds-z-header);
  background: color-mix(in oklab, var(--wds-bg) 88%, transparent);
  backdrop-filter: blur(var(--wds-blur-md));
  border-bottom: var(--wds-border-hairline) solid var(--wds-border-subtle);
}
.wds-header__inner {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: var(--wds-space-6);
  min-height: 56px;
}
.wds-nav { display: flex; gap: var(--wds-space-5); align-items: center; }
.wds-nav a {
  color: var(--wds-fg-secondary);
  text-decoration: none;
  font-size: var(--wds-text-caption);
  letter-spacing: var(--wds-tracking-wide);
  padding-block: var(--wds-space-2);
}
.wds-nav a:hover, .wds-nav a[aria-current='page'] { color: var(--wds-fg); }
.wds-nav a[aria-current='page'] { box-shadow: inset 0 -1px 0 var(--wds-accent); }

/* Mobile nav without JavaScript: native <details> as a disclosure. */
.wds-nav-toggle { display: none; }
@media (max-width: 719px) {
  .wds-nav { display: none; }
  .wds-nav-toggle { display: block; }
  .wds-nav-toggle[open] .wds-nav { display: flex; flex-direction: column; }
  .wds-nav-toggle > summary {
    list-style: none; cursor: pointer;
    min-height: var(--wds-touch-target);
    display: flex; align-items: center;
  }
  .wds-nav-toggle > summary::-webkit-details-marker { display: none; }
}

/* --------------------------------------------------------------- hero -- */
.wds-hero { padding-block: var(--wds-space-16) var(--wds-space-14); }
.wds-hero__title {
  font-size: var(--wds-text-display);
  font-weight: var(--wds-weight-light);
  letter-spacing: var(--wds-tracking-tight);
}
.wds-hero__lead {
  font-size: var(--wds-text-lead);
  color: var(--wds-fg-secondary);
  max-width: var(--wds-reading);
}

/* ------------------------------------------------------------ tables --- */
.wds-table { width: 100%; border-collapse: collapse; font-size: var(--wds-text-caption); }
.wds-table th {
  text-align: left;
  font-weight: var(--wds-weight-medium);
  color: var(--wds-fg-tertiary);
  letter-spacing: var(--wds-tracking-wide);
  padding: var(--wds-space-3) var(--wds-space-4) var(--wds-space-3) 0;
  border-bottom: var(--wds-border-thin) solid var(--wds-border);
}
.wds-table td {
  padding: var(--wds-space-3) var(--wds-space-4) var(--wds-space-3) 0;
  border-bottom: var(--wds-border-hairline) solid var(--wds-border-subtle);
}
.wds-table tr:hover td { background: var(--wds-surface); }
.wds-table-wrap { overflow-x: auto; }

/* ------------------------------------------------------------- code ---- */
.wds-code {
  background: var(--wds-code-bg);
  border: var(--wds-border-hairline) solid var(--wds-border-subtle);
  border-radius: var(--wds-radius-md);
  padding: var(--wds-space-4) var(--wds-space-5);
  overflow-x: auto;
  max-width: var(--wds-code-width);
  line-height: var(--wds-leading-snug);
}
.wds-code code { background: none; border: 0; padding: 0; }

/* ------------------------------------------------------------ inputs --- */
.wds-field { display: grid; gap: var(--wds-space-2); margin-bottom: var(--wds-space-5); }
.wds-label {
  font-size: var(--wds-text-caption);
  color: var(--wds-fg-secondary);
  letter-spacing: var(--wds-tracking-wide);
}
.wds-input, .wds-textarea, .wds-select {
  width: 100%;
  min-height: var(--wds-touch-target);
  padding: var(--wds-space-3) var(--wds-space-4);
  background: var(--wds-surface);
  color: var(--wds-fg);
  border: var(--wds-border-thin) solid var(--wds-border);
  border-radius: var(--wds-radius-md);
  font: inherit;
  transition: border-color var(--wds-duration-fast) var(--wds-ease-standard);
}
.wds-input:hover, .wds-textarea:hover { border-color: var(--wds-border-strong); }
.wds-input::placeholder { color: var(--wds-fg-quiet); }
.wds-input[aria-invalid='true'] { border-color: var(--wds-danger); }
.wds-help { font-size: var(--wds-text-caption); color: var(--wds-fg-tertiary); }
.wds-error { font-size: var(--wds-text-caption); color: var(--wds-danger); }

/* --------------------------------------------------- accordion / tabs -- */
/* Native <details>: keyboard accessible with no script. */
.wds-accordion {
  border-bottom: var(--wds-border-hairline) solid var(--wds-border-subtle);
}
.wds-accordion > summary {
  cursor: pointer;
  padding: var(--wds-space-4) 0;
  min-height: var(--wds-touch-target);
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: var(--wds-space-4);
  font-weight: var(--wds-weight-medium);
  list-style: none;
}
.wds-accordion > summary::-webkit-details-marker { display: none; }
.wds-accordion > summary::after {
  content: '+';
  font-family: var(--wds-font-mono);
  color: var(--wds-accent);
  transition: transform var(--wds-duration-base) var(--wds-ease-standard);
}
.wds-accordion[open] > summary::after { transform: rotate(45deg); }
.wds-accordion__body { padding-bottom: var(--wds-space-4); color: var(--wds-fg-secondary); }

/* ------------------------------------------------------------ dialog --- */
/* Native <dialog>: showModal() is one line of platform code, not a framework. */
.wds-dialog {
  background: var(--wds-surface-elevated);
  color: var(--wds-fg);
  border: var(--wds-border-thin) solid var(--wds-border);
  border-radius: var(--wds-radius-xl);
  padding: var(--wds-space-8);
  max-width: 32rem;
  box-shadow: var(--wds-shadow-modal);
}
.wds-dialog::backdrop {
  background: rgb(0 0 0 / var(--wds-opacity-scrim));
  backdrop-filter: blur(var(--wds-blur-sm));
}

/* ----------------------------------------------------------- tooltip --- */
/* CSS-only: the trigger owns the state. No positioning engine, so it is
   deliberately limited to short labels in open space. */
.wds-tooltip { position: relative; display: inline-flex; }
.wds-tooltip__bubble {
  position: absolute;
  bottom: calc(100% + var(--wds-space-2));
  left: 50%;
  translate: -50% 0;
  z-index: var(--wds-z-tooltip);
  padding: var(--wds-space-2) var(--wds-space-3);
  background: var(--wds-surface-elevated);
  border: var(--wds-border-hairline) solid var(--wds-border);
  border-radius: var(--wds-radius-sm);
  font-size: var(--wds-text-caption);
  white-space: nowrap;
  opacity: 0;
  pointer-events: none;
  transition: opacity var(--wds-duration-fast) var(--wds-ease-standard);
}
.wds-tooltip:hover .wds-tooltip__bubble,
.wds-tooltip:focus-within .wds-tooltip__bubble { opacity: 1; }

/* ---------------------------------------------------------- timeline --- */
.wds-timeline { list-style: none; margin: 0; padding: 0; }
.wds-timeline li {
  position: relative;
  padding-left: var(--wds-space-8);
  padding-bottom: var(--wds-space-8);
  border-left: var(--wds-border-thin) solid var(--wds-border-subtle);
  margin-left: var(--wds-space-2);
}
.wds-timeline li::before {
  content: '';
  position: absolute;
  left: -4px; top: 6px;
  width: 7px; height: 7px;
  border-radius: 50%;
  background: var(--wds-accent);
}
.wds-timeline li:last-child { border-left-color: transparent; padding-bottom: 0; }

/* ----------------------------------------------------------- metrics --- */
.wds-metrics {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(9rem, 1fr));
  gap: var(--wds-space-6);
}
.wds-metric__value {
  font-size: var(--wds-text-h2);
  font-weight: var(--wds-weight-light);
  font-variant-numeric: tabular-nums;
  letter-spacing: var(--wds-tracking-tight);
}
.wds-metric__label {
  font-family: var(--wds-font-mono);
  font-size: var(--wds-text-caption);
  color: var(--wds-fg-tertiary);
  letter-spacing: var(--wds-tracking-wide);
}

/* ------------------------------------------------- states & skeletons -- */
.wds-empty, .wds-error-state {
  text-align: center;
  padding: var(--wds-space-16) var(--wds-space-6);
  color: var(--wds-fg-tertiary);
  border: var(--wds-border-thin) dashed var(--wds-border-subtle);
  border-radius: var(--wds-radius-lg);
}
.wds-skeleton {
  background: linear-gradient(90deg,
    var(--wds-surface) 25%,
    var(--wds-surface-elevated) 37%,
    var(--wds-surface) 63%);
  background-size: 400% 100%;
  border-radius: var(--wds-radius-sm);
  animation: wds-shimmer 1.4s ease-in-out infinite;
}
@keyframes wds-shimmer { to { background-position: -135% 0; } }
@media (prefers-reduced-motion: reduce) {
  .wds-skeleton { animation: none; background: var(--wds-surface); }
}

.wds-progress {
  width: 100%; height: 4px;
  background: var(--wds-surface);
  border-radius: var(--wds-radius-pill);
  overflow: hidden;
}
.wds-progress__bar { height: 100%; background: var(--wds-accent); }

/* -------------------------------------------------------- breadcrumbs -- */
.wds-breadcrumbs {
  display: flex; flex-wrap: wrap; gap: var(--wds-space-2);
  font-size: var(--wds-text-caption);
  color: var(--wds-fg-tertiary);
  list-style: none; padding: 0; margin: 0;
}
.wds-breadcrumbs li + li::before { content: '/'; margin-right: var(--wds-space-2); opacity: 0.5; }

/* -------------------------------------------------------- pagination --- */
.wds-pagination { display: flex; gap: var(--wds-space-2); align-items: center; }
.wds-pagination a, .wds-pagination span {
  min-width: var(--wds-touch-target);
  min-height: var(--wds-touch-target);
  display: inline-flex; align-items: center; justify-content: center;
  border-radius: var(--wds-radius-md);
  text-decoration: none;
  font-variant-numeric: tabular-nums;
}
.wds-pagination a:hover { background: var(--wds-surface); }
.wds-pagination [aria-current='page'] {
  background: var(--wds-surface-interactive);
  color: var(--wds-fg);
}

/* ------------------------------------------------------------ footer --- */
.wds-footer {
  border-top: var(--wds-border-hairline) solid var(--wds-border-subtle);
  padding-block: var(--wds-space-12);
  color: var(--wds-fg-tertiary);
  font-size: var(--wds-text-caption);
}

/* -------------------------------------------------------- the glyph ---- */
/* Consumed from the IPS. Never redrawn. Sized so its cap height matches the
   surrounding text, and seated exactly on the baseline. */
.wds-glyph {
  display: inline-block;
  height: 0.70em;
  width: auto;
  vertical-align: 0;
}
.wds-glyph path { fill: none; stroke: currentColor; }
.wds-mark { display: inline-flex; align-items: center; gap: var(--wds-space-2); }

/* --------------------------------------------------------- utilities --- */
.wds-visually-hidden {
  position: absolute; width: 1px; height: 1px;
  padding: 0; margin: -1px; overflow: hidden;
  clip-path: inset(50%); white-space: nowrap; border: 0;
}
.wds-skip-link {
  position: absolute; top: var(--wds-space-2); left: var(--wds-space-2);
  z-index: var(--wds-z-toast);
  padding: var(--wds-space-3) var(--wds-space-4);
  background: var(--wds-surface-elevated);
  border: var(--wds-border-thin) solid var(--wds-border-strong);
  border-radius: var(--wds-radius-md);
  transform: translateY(-200%);
}
.wds-skip-link:focus { transform: translateY(0); }
"""
