# -*- coding: utf-8 -*-
"""
WEBSITE DESIGN SYSTEM - build

    CDS -> IPS -> WDS -> components -> pages

The WDS consumes the identity. It never modifies it: cds.json is opened
read-only and its digest is checked, so a drifted identity stops the build.

Run:  python build_wds.py
"""

import hashlib
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from core.derive import load_tokens, derive, validate
from core.css import emit_tokens, emit_base, emit_components, type_scale
from core.docs import build_docs

HERE = os.path.dirname(os.path.abspath(__file__))

# The living documentation is emitted to both locations from one render, so the
# two can never drift. The second is outside the package on purpose: it is where
# the page is read from, and a hand-made copy there has already gone stale once.
DOC_TARGETS = [
    os.path.join(HERE, "docs", "index.html"),
    os.path.join(os.path.dirname(HERE), "paleta_canonica",
                 "paleta_canonica.html"),
]


def resolve_cds():
    """
    Resolves the CDS path. The canonical location is the sibling identity/
    package: the WDS consumes the real specification, never a private copy.
    Two copies of a single source of truth can drift, which is the one thing
    the CDS exists to prevent.
    """
    candidates = [
        os.path.join(os.path.dirname(HERE), "identity", "cds.json"),
        os.path.join(HERE, "cds.json"),
    ]
    for p in candidates:
        if os.path.isfile(p):
            return p
    raise SystemExit(
        "WDS ABORT: no CDS found. Expected ../identity/cds.json. "
        "The WDS cannot build without the identity it consumes.")


def main():
    print("=" * 74)
    print("WEBSITE DESIGN SYSTEM — build")
    print("=" * 74)

    # ---- consume the identity, read-only ---------------------------------
    cds_path = resolve_cds()
    with open(cds_path, encoding="utf-8") as f:
        cds = json.load(f)
    d = cds["path"]["d"]
    digest = hashlib.sha256(d.encode("utf-8")).hexdigest()
    if digest != cds["path"]["sha256"]:
        raise SystemExit("WDS ABORT: the consumed identity has drifted.")
    print(f"\n  consuming CDS {cds['cds_version']} — "
          f"{cds['identity']['canonical_glyph']}")
    print(f"  identity digest verified: {digest[:32]}...")
    print(f"  source: {os.path.relpath(cds_path, HERE)}")

    tok = load_tokens()
    col = derive(tok)

    # ---- validate every contrast contract --------------------------------
    rows, failures = validate(col)
    print(f"\n  colour contracts: {len(rows) - len(failures)}/{len(rows)} met")
    if failures:
        print("\n  BUILD HALTED — a design system does not ship failing contrast.")
        for f_ in failures:
            print(f"    - {f_}")
        return 1

    m = col["meta"]
    print(f"  semantic colours derived by hue rotation from the canonical accent")
    for n, s in m["semantic"].items():
        print(f"    {n:<9} {s['hex']}  rot {s['rotation']:>6.1f}deg  H={s['H']:6.1f}")
    sep = m["min_hue_separation"]
    print(f"  minimum hue separation: {sep['degrees']:.1f}deg "
          f"({sep['between'][0]} / {sep['between'][1]})")
    for k, v in m.get("solved", {}).items():
        print(f"  solved for contract: {k} -> {v['hex']} at {v['ratio']}:1")

    # ---- emit ------------------------------------------------------------
    css_dir = os.path.join(HERE, "css")
    os.makedirs(css_dir, exist_ok=True)
    files = {
        "tokens.css": emit_tokens(tok, col),
        "base.css": emit_base(tok),
        "components.css": emit_components(tok),
    }
    files["wds.css"] = (
        "/* Single entry point. Generated by the WDS. */\n"
        + files["tokens.css"] + "\n" + files["base.css"] + "\n"
        + files["components.css"])

    for name, text in files.items():
        with open(os.path.join(css_dir, name), "w",
                  encoding="utf-8", newline="\n") as f:
            f.write(text)

    print("\n  css emitted")
    for name, text in files.items():
        b = len(text.encode("utf-8"))
        import gzip
        gz = len(gzip.compress(text.encode("utf-8"), 9, mtime=0))
        print(f"    css/{name:<18} {b:>6} B   gzip {gz:>5} B")

    # ---- type scale report ------------------------------------------------
    print("\n  type scale (ratio "
          f"{tok['type_scale']['ratio']}, base {tok['type_scale']['base_px']}px)")
    for name, mn, mx, _ in type_scale(tok):
        print(f"    {name:<10} {mn:6.1f}px -> {mx:6.1f}px")

    # ---- docs -------------------------------------------------------------
    # The stylesheet is inlined rather than linked: a relative href only
    # resolves from the directory it was written for, so a linked page loses
    # every style the moment it is moved. One render, two destinations.
    docs = build_docs(tok, col, cds, rows, files["wds.css"])
    print(f"\n  docs rendered        {len(docs.encode('utf-8')):>6} B "
          f"(self-contained: css inlined)")
    for target in DOC_TARGETS:
        os.makedirs(os.path.dirname(target), exist_ok=True)
        with open(target, "w", encoding="utf-8", newline="\n") as f:
            f.write(docs)
        print(f"    {os.path.relpath(target, HERE)}")

    # ---- token export for tooling ----------------------------------------
    export = {"wds_version": tok["wds_version"],
              "consumes": tok["consumes"],
              "colours": {k: v for k, v in col.items() if k != "meta"},
              "meta": col["meta"],
              "contrast_report": rows}
    with open(os.path.join(HERE, "tokens.resolved.json"), "w",
              encoding="utf-8", newline="\n") as f:
        json.dump(export, f, indent=2, sort_keys=True)
        f.write("\n")

    # ---- release manifest: hashes, so drift is detectable ----------------
    manifest = {}
    for name, text in sorted(files.items()):
        raw = text.encode("utf-8")
        manifest[f"css/{name}"] = {
            "bytes": len(raw),
            "sha256": hashlib.sha256(raw).hexdigest(),
        }
    docs_raw = docs.encode("utf-8")
    for target in DOC_TARGETS:
        key = os.path.relpath(target, HERE).replace(os.sep, "/")
        manifest[key] = {
            "bytes": len(docs_raw),
            "sha256": hashlib.sha256(docs_raw).hexdigest(),
        }
    release = {
        "wds_version": tok["wds_version"],
        "consumes_cds_version": cds["cds_version"],
        "consumes_glyph": cds["identity"]["canonical_glyph"],
        "consumes_path_sha256": cds["path"]["sha256"],
        "contrast_contracts": {"checked": len(rows), "met": len(rows)},
        "artefacts": manifest,
    }
    release["release_digest"] = hashlib.sha256(
        json.dumps(manifest, sort_keys=True,
                   separators=(",", ":")).encode("utf-8")).hexdigest()
    with open(os.path.join(HERE, "WDS-RELEASE.json"), "w",
              encoding="utf-8", newline="\n") as f:
        json.dump(release, f, indent=2, sort_keys=True)
        f.write("\n")

    print("\n" + "=" * 74)
    print("  WDS BUILD OK")
    print(f"  release digest: {release['release_digest']}")
    print("=" * 74)
    return 0


if __name__ == "__main__":
    sys.exit(main())
