# -*- coding: utf-8 -*-
"""
Site-specific CSS: composition, not tokens.

Every colour, size, radius and duration below is a var(--wds-*) already
derived and contrast-checked by the WDS. This file only arranges them into
shapes the WDS component library does not already provide -- hero, pillars,
the technology grid, editorial lists, the CV gate, and the WhatsApp float.

Everything here uses the "site-" prefix so the vocabulary never mixes with
"wds-": the site composes the design system, it does not extend it.
"""

SITE_CSS = """
/* Generated by site/build_site.py. Do not edit by hand. */

/* Language changes remain real document navigations. A very short opacity
   transition softens the visual replacement without turning the site into
   a client-side router. */
/* Reserve the scrollbar track whether or not this page needs to scroll.
   Without it the header and every container shift 8px sideways when moving
   between a page that scrolls and one that does not -- the kind of drift
   that reads as "these pages are laid out differently". */
html { background: var(--wds-bg); scrollbar-gutter: stable; }

/* The page is a column that always fills the window, so the footer closes
   the document instead of stopping wherever the content happened to end.
   Without this, a short page (every detail page, every index) left a band
   below the footer -- and the band was VISIBLE because html paints a flat
   colour while body paints the ambient gradient, so the two grounds met at
   the end of the body box. svh, not vh, so a mobile URL bar cannot push the
   column past the viewport and invent a scrollbar. */
body { min-height: 100vh; min-height: 100svh; display: flex; flex-direction: column; }
main { flex: 1 0 auto; }

html.site-language-leaving body,
html.site-language-arriving body { opacity: 0; }
/* One declaration covers both movements the page can make: the language
   cross-fade, and the theme change -- which is a colour change, so it eases
   on colour rather than on opacity. */
body {
  transition: opacity 130ms var(--wds-ease-standard),
              background-color var(--wds-duration-base) var(--wds-ease-standard),
              color var(--wds-duration-base) var(--wds-ease-standard);
}
.wds-header, .wds-footer, .site-editorial article, .site-cv-stats {
  transition: border-color var(--wds-duration-base) var(--wds-ease-standard),
              background-color var(--wds-duration-base) var(--wds-ease-standard);
}
@media (prefers-reduced-motion: reduce) {
  body { transition: none; }
}

/* ---------------------------------------------------------- header ----- */
/* The brand mark became a link to Home in Phase 2 (spec S5: "Juan Felipe
   links to /"). a.wds-mark would otherwise inherit the global link colour
   from base.css and turn the wordmark orange -- override back to the plain
   foreground so the header keeps its original, quieter look. */
a.wds-mark { color: var(--wds-fg); text-decoration: none; }
a.wds-mark:hover { color: var(--wds-accent); }
a.wds-mark .wds-glyph { height: 1.12em; }

.site-nav-group {
  display: flex;
  align-items: center;
  gap: var(--wds-space-6);
}

/* One segmented control, two instances: language and theme. Both are a
   choice between two states of the same page, so they share a shape -- the
   theme switch reads as part of the navigation, not as a widget bolted on. */
.site-switch {
  display: flex;
  gap: var(--wds-space-1);
  font-family: var(--wds-font-mono);
  font-size: var(--wds-text-caption);
  letter-spacing: var(--wds-tracking-wide);
}
.site-switch a, .site-switch span, .site-switch button {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-height: 28px;
  padding: var(--wds-space-1) var(--wds-space-2);
  border-radius: var(--wds-radius-sm);
}
.site-switch a, .site-switch button {
  color: var(--wds-fg-tertiary);
  text-decoration: none;
  transition: color var(--wds-duration-fast) var(--wds-ease-standard),
              background-color var(--wds-duration-fast) var(--wds-ease-standard);
}
.site-switch button {
  min-width: 30px;
  font: inherit;
  letter-spacing: inherit;
  background: none;
  border: 0;
  cursor: pointer;
}
.site-switch a:hover, .site-switch button:hover { color: var(--wds-accent); }
/* Active state is carried by aria-current / aria-pressed, so the styling and
   the accessibility tree can never disagree about which option is on. */
.site-switch span[aria-current], .site-switch button[aria-pressed='true'] {
  color: var(--wds-fg);
  font-weight: var(--wds-weight-semibold);
  background: var(--wds-surface-interactive);
}
.site-switch svg { flex: 0 0 auto; }

/* Two switches plus the menu disclosure have to share a 320px bar with the
   wordmark. The controls tighten rather than wrap: padding comes off the
   sides, never off the 24px minimum target both dimensions must keep. */
@media (max-width: 719px) {
  .site-nav-group { gap: var(--wds-space-3); }
  .site-switch { gap: 0; }
  .site-switch a, .site-switch span, .site-switch button {
    padding-inline: var(--wds-space-1);
    min-width: 26px;
  }
  .site-switch button { min-width: 30px; }
}

/* ---------------------------------------------------------- eyebrow ---- */
.site-eyebrow {
  font-family: var(--wds-font-mono);
  font-size: var(--wds-text-caption);
  letter-spacing: var(--wds-tracking-caps);
  color: var(--wds-accent);
  text-transform: uppercase;
  margin: 0 0 var(--wds-space-3);
}

/* ------------------------------------------------------------- hero ---- */
/* The hero is the name alone. Its lower padding was sized for a second line
   that no longer exists -- reduced here so the first section follows the
   name at a readable distance instead of across a gap. */
.site-hero { padding-block: var(--wds-space-20) var(--wds-space-6); }
.site-hero__name {
  margin: 0;
  font-size: var(--wds-text-display);
  font-weight: var(--wds-weight-light);
  letter-spacing: var(--wds-tracking-tight);
}

/* --------------------------------------------------------- what i do --- */
.site-pillars {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: var(--wds-space-10);
}
.site-pillar__title {
  font-family: var(--wds-font-mono);
  font-size: var(--wds-text-caption);
  letter-spacing: var(--wds-tracking-caps);
  text-transform: uppercase;
  color: var(--wds-fg);
  margin: 0 0 var(--wds-space-3);
}
.site-pillar__body { color: var(--wds-fg-secondary); margin: 0; }
@media (max-width: 719px) {
  .site-pillars { grid-template-columns: 1fr; gap: var(--wds-space-8); }
}

/* ----------------------------------------------------- technologies ---- */
.site-tech {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: var(--wds-space-8);
}
.site-tech__group-title {
  font-family: var(--wds-font-mono);
  font-size: var(--wds-text-caption);
  letter-spacing: var(--wds-tracking-caps);
  text-transform: uppercase;
  color: var(--wds-fg);
  font-weight: var(--wds-weight-semibold);
  margin: 0 0 var(--wds-space-3);
}
.site-tech__list { list-style: none; margin: 0; padding: 0; }
.site-tech__list li {
  padding-block: var(--wds-space-1);
  color: var(--wds-fg-secondary);
}
@media (max-width: 1023px) {
  .site-tech { grid-template-columns: repeat(2, 1fr); }
}
@media (max-width: 719px) {
  .site-tech { grid-template-columns: 1fr; gap: var(--wds-space-6); }
}

/* ---------------------------------------------- editorial list (work/lab) */
.site-editorial { list-style: none; margin: 0; padding: 0; }
.site-editorial > li + li { margin-top: var(--wds-space-10); }
.site-editorial article {
  padding-top: var(--wds-space-8);
  border-top: var(--wds-border-hairline) solid var(--wds-border-subtle);
}
.site-editorial article:first-child { border-top: 0; padding-top: 0; }
.site-editorial__title {
  margin: 0 0 var(--wds-space-2);
  font-size: var(--wds-text-h3);
  font-weight: var(--wds-weight-semibold);
}
.site-editorial__title a { color: inherit; text-decoration: none; }
.site-editorial__title a:hover { color: var(--wds-accent); }
.site-editorial__meta {
  font-family: var(--wds-font-mono);
  font-size: var(--wds-text-caption);
  letter-spacing: var(--wds-tracking-wide);
  color: var(--wds-fg-tertiary);
  margin: 0 0 var(--wds-space-4);
}
.site-editorial__body { color: var(--wds-fg-secondary); max-width: var(--wds-reading); }
.site-editorial__more { margin-top: var(--wds-space-8); }
.site-editorial__more a { font-family: var(--wds-font-mono); font-size: var(--wds-text-caption); }

/* --------------------------------------------------------------- gate --- */
.site-gate__body { color: var(--wds-fg-secondary); max-width: var(--wds-reading); }
.site-gate__link {
  display: inline-block;
  margin-top: var(--wds-space-4);
  font-family: var(--wds-font-mono);
  font-size: var(--wds-text-caption);
  letter-spacing: var(--wds-tracking-wide);
}

/* ------------------------------------------------------------- footer --- */
/* Identity, year and contact on one line. The row stays left-aligned on
   purpose: the WhatsApp float occupies the bottom-right corner, and a link
   parked underneath it is a link nobody can press. */
.wds-footer { padding-block: var(--wds-space-8); }
.site-footer {
  display: flex;
  flex-wrap: wrap;
  align-items: baseline;
  gap: var(--wds-space-2) var(--wds-space-8);
  font-family: var(--wds-font-mono);
}
.site-footer__id { margin: 0; max-width: none; }
.site-footer__links {
  display: flex;
  flex-wrap: wrap;
  gap: var(--wds-space-2) var(--wds-space-4);
  margin: 0;
  padding: 0;
  list-style: none;
}
.site-footer__links li { margin-bottom: 0; }
.site-footer__links a { padding-block: var(--wds-space-1); }

/* --------------------------------------------------------- whatsapp ---- */
/* Recognizable WhatsApp glyph, intentionally rendered with the site accent
   rather than WhatsApp green so the contact action remains subordinate to
   the canonical arjuanfelipe.com colour system. */
.site-whatsapp {
  position: fixed;
  right: max(var(--wds-space-6), env(safe-area-inset-right));
  bottom: max(var(--wds-space-6), env(safe-area-inset-bottom));
  z-index: var(--wds-z-toast);
  display: inline-flex;
  align-items: center;
  gap: var(--wds-space-2);
  justify-content: center;
  min-width: 64px;
  min-height: 64px;
  padding: var(--wds-space-4);
  border-radius: var(--wds-radius-pill);
  background: var(--wds-surface-elevated);
  border: var(--wds-border-thin) solid var(--wds-border);
  color: var(--wds-fg);
  text-decoration: none;
  box-shadow: 0 6px 20px rgb(0 0 0 / 0.28);
  transition: border-color var(--wds-duration-fast) var(--wds-ease-standard),
              background-color var(--wds-duration-fast) var(--wds-ease-standard),
              box-shadow var(--wds-duration-base) var(--wds-ease-standard);
}
/* Shadow depth is a property of the light in the room, not of the palette:
   the same 28% black that separates the float from a charcoal page turns to
   soot on a near-white one. Only the opacity moves. */
:root[data-theme='light'] .site-whatsapp { box-shadow: 0 6px 20px rgb(0 0 0 / 0.10); }
.site-whatsapp:hover, .site-whatsapp:focus-visible {
  border-color: var(--wds-accent);
  background: var(--wds-surface-interactive);
}
.site-whatsapp__inner {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: var(--wds-space-2);
  margin-inline: auto;
}
.site-whatsapp svg {
  width: 28px;
  height: 28px;
  flex: 0 0 auto;
  color: var(--wds-accent);
  /* The speech-bubble tail makes the path look left-heavy even when its
     SVG box is mathematically centered. This is an optical correction. */
  transform: translateX(1.5px);
}
.site-whatsapp__label {
  font-family: var(--wds-font-mono);
  font-size: var(--wds-text-caption);
  max-width: 0;
  overflow: hidden;
  white-space: nowrap;
  opacity: 0;
  transition: max-width var(--wds-duration-base) var(--wds-ease-standard),
              opacity var(--wds-duration-fast) var(--wds-ease-standard);
}
.site-whatsapp:hover .site-whatsapp__label,
.site-whatsapp:focus-visible .site-whatsapp__label {
  max-width: 12rem;
  opacity: 1;
}
@media (prefers-reduced-motion: reduce) {
  .site-whatsapp, .site-whatsapp__label { transition: none; }
}

/* ------------------------------------------------------ detail pages --- */
.site-detail__back {
  display: inline-block;
  margin-bottom: var(--wds-space-8);
  font-family: var(--wds-font-mono);
  font-size: var(--wds-text-caption);
}
.site-detail__meta {
  font-family: var(--wds-font-mono);
  font-size: var(--wds-text-caption);
  letter-spacing: var(--wds-tracking-wide);
  color: var(--wds-fg-tertiary);
  margin: var(--wds-space-3) 0 var(--wds-space-6);
}
.site-detail__body { color: var(--wds-fg-secondary); max-width: var(--wds-reading); }
.site-detail__tech {
  margin-top: var(--wds-space-6);
  font-family: var(--wds-font-mono);
  font-size: var(--wds-text-caption);
  color: var(--wds-fg-tertiary);
}

/* ------------------------------------------------------------------ CV - */
.site-cv-identity { padding-block: var(--wds-space-16) var(--wds-space-10); }
.site-cv-identity__name {
  margin: 0 0 var(--wds-space-3);
  font-size: var(--wds-text-h1);
  font-weight: var(--wds-weight-semibold);
  letter-spacing: var(--wds-tracking-tight);
}
.site-cv-stats {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: var(--wds-space-8);
  padding: var(--wds-space-8) 0;
  border-top: var(--wds-border-hairline) solid var(--wds-border-subtle);
  border-bottom: var(--wds-border-hairline) solid var(--wds-border-subtle);
}
.site-cv-stats__value {
  font-size: var(--wds-text-h2);
  font-weight: var(--wds-weight-light);
  font-variant-numeric: tabular-nums;
  letter-spacing: var(--wds-tracking-tight);
  color: var(--wds-accent);
}
.site-cv-stats__label {
  font-family: var(--wds-font-mono);
  font-size: var(--wds-text-caption);
  color: var(--wds-fg-tertiary);
}
@media (max-width: 719px) {
  .site-cv-stats { grid-template-columns: 1fr; gap: var(--wds-space-4); }
}

.site-cv-entry { margin-bottom: var(--wds-space-8); }
.site-cv-entry:last-child { margin-bottom: 0; }
.site-cv-entry__role {
  margin: 0;
  font-size: var(--wds-text-h4);
  font-weight: var(--wds-weight-semibold);
}
.site-cv-entry__company { color: var(--wds-fg-secondary); margin: var(--wds-space-1) 0; }
.site-cv-entry__dates {
  font-family: var(--wds-font-mono);
  font-size: var(--wds-text-caption);
  color: var(--wds-fg-tertiary);
  margin: 0 0 var(--wds-space-3);
}
.site-cv-entry__achievement { color: var(--wds-fg); max-width: var(--wds-reading); margin: 0 0 var(--wds-space-3); }
.site-cv-entry__achievement strong, .site-cv-entry__areas strong { color: var(--wds-accent); }
.site-cv-entry__areas { color: var(--wds-fg-secondary); max-width: var(--wds-reading); margin: 0; }
/* Added for the new tech_stack field -- its own rule, so the shared
   selectors above stay exactly as they were. */
.site-cv-entry__tech {
  color: var(--wds-fg-secondary);
  margin: 0 0 var(--wds-space-3);
  text-align: left !important;
  hyphens: none !important;
  -webkit-hyphens: none !important;
}
.site-cv-entry__tech strong { color: var(--wds-accent); }

.site-cv-print-only { display: none; }

@media print {
  .wds-header, .site-whatsapp, .wds-skip-link, .site-lang-switch { display: none !important; }
  .site-cv-print-only { display: block; }
  /* Back to normal flow on paper: the viewport column has no meaning there,
     and flex containers break pagination in several print engines. */
  body { background: #fff; color: #111; display: block; min-height: 0; }
  main { flex: none; }
  a { color: #111; text-decoration: underline; }
  .wds-section { padding-block: 0.5cm; }
  .site-cv-identity { padding-block: 0 0.5cm; }
  .site-cv-entry { break-inside: avoid; }
  .site-cv-stats { border-color: #999; }
  /* The accent orange is only ~3.26:1 on white -- borderline even for large
     text. Print gets no second chance to squint at a screen, so pin it to
     solid black rather than leave a marginal ratio in a PDF someone keeps. */
  .site-cv-stats__value, .site-eyebrow { color: #111 !important; }
  .wds-footer { border-top-color: #999; color: #444; }
  @page { margin: 1.6cm; }
}


/* --------------------------------------------- ambient surface layer --- */
/* Recover the quiet depth from the early site without turning the accent
   into decoration. The radial uses only neighbouring charcoal values and
   is anchored to the viewport so long pages do not repeat the effect. */
body {
  background:
    radial-gradient(
      ellipse 90vw 80vh at 38vw 40vh,
      var(--wds-surface) 0%,
      var(--wds-bg) 100%
    ) fixed;
}

/* The early visual language also let the accent contaminate hairlines very
   slightly. Keep this restrained: orange remains an identity cue, not a
   frame around the content. */
.wds-header,
.wds-footer,
.site-editorial article,
.site-cv-stats {
  border-color: color-mix(in srgb, var(--wds-accent) 18%, var(--wds-border-subtle));
}

/* Classification metadata stays neutral. Orange is reserved for section
   eyebrows and interaction states, keeping the accent scarce and intentional. */
.site-editorial__meta,
.site-detail__meta {
  color: var(--wds-fg-tertiary);
}

@media print {
  body { background: #fff !important; }
}

/* ------------------------------------------------ editorial rhythm ----- */
/* Long-form prose is justified across the public site. Hyphenation and a
   left-aligned final line reduce the wide gaps that full justification can
   otherwise create, especially in Spanish. Metadata/navigation remain left
   aligned because they are labels, not prose. */
main p:not(.site-eyebrow):not(.site-editorial__meta):not(.site-detail__meta):not(.site-detail__back):not(.site-cv-entry__company):not(.site-cv-entry__dates):not(.site-cv-print-only) {
  text-align: justify;
  text-align-last: left;
  hyphens: auto;
  -webkit-hyphens: auto;
}

/* Tighter internal rhythm: related text stays together while sections keep
   the larger WDS spacing that separates ideas. */
.site-pillar__body,
.site-editorial__body,
.site-detail__body,
.site-gate__body,
.site-cv-entry__achievement,
.site-cv-entry__areas {
  line-height: 1.65;
}

.site-editorial__body { margin-bottom: 0; }
.site-cv-entry { margin-bottom: var(--wds-space-10); }
.site-cv-entry__role { margin-bottom: var(--wds-space-1); }
.site-cv-entry__company { margin: 0 0 var(--wds-space-1); }
.site-cv-entry__dates { margin-bottom: var(--wds-space-4); }
.site-cv-entry__achievement { margin-bottom: var(--wds-space-4); }
.site-cv-entry__areas { margin-bottom: 0; }

/* On very narrow screens full justification creates distracting rivers and
   oversized word gaps. Preserve the requested justified treatment from
   tablet upward, but prioritize readability on small phones. */
@media (max-width: 479px) {
  main p:not(.site-eyebrow):not(.site-editorial__meta):not(.site-detail__meta):not(.site-detail__back):not(.site-cv-entry__company):not(.site-cv-entry__dates):not(.site-cv-print-only) {
    text-align: left;
  }
}

/* --------------------------------------------------- applications ------ */
/* A grid of cards, each the click target for a live app on its own domain.
   Same vocabulary as the rest of the site: mono labels, accent reserved for
   the eyebrow and interaction, hairlines tinted with the identity orange. */
.site-apps__back {
  display: inline-block;
  margin-bottom: var(--wds-space-8);
  font-family: var(--wds-font-mono);
  font-size: var(--wds-text-caption);
}
.site-apps {
  list-style: none;
  margin: var(--wds-space-10) 0 0;
  padding: 0;
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: var(--wds-space-8);
}
.site-apps__card {
  display: flex;
  flex-direction: column;
  height: 100%;
  padding: var(--wds-space-4);
  border: var(--wds-border-hairline) solid
    color-mix(in srgb, var(--wds-accent) 18%, var(--wds-border-subtle));
  border-radius: var(--wds-radius-md);
  background: var(--wds-surface);
  color: inherit;
  text-decoration: none;
  transition: border-color var(--wds-duration-fast) var(--wds-ease-standard),
              background-color var(--wds-duration-fast) var(--wds-ease-standard),
              transform var(--wds-duration-fast) var(--wds-ease-standard);
}
.site-apps__card:hover,
.site-apps__card:focus-visible {
  border-color: var(--wds-accent);
  background: var(--wds-surface-elevated);
}
.site-apps__preview {
  display: block;
  aspect-ratio: 2 / 1;
  overflow: hidden;
  border-radius: var(--wds-radius-sm);
  background: var(--wds-surface-interactive);
}
.site-apps__preview img {
  display: block;
  width: 100%;
  height: 100%;
  object-fit: cover;
}
.site-apps__name {
  margin-top: var(--wds-space-4);
  font-size: var(--wds-text-h4);
  font-weight: var(--wds-weight-semibold);
}
.site-apps__meta {
  margin-top: var(--wds-space-2);
  font-family: var(--wds-font-mono);
  font-size: var(--wds-text-caption);
  letter-spacing: var(--wds-tracking-wide);
  color: var(--wds-fg-tertiary);
}
.site-apps__body {
  margin-top: var(--wds-space-3);
  color: var(--wds-fg-secondary);
  line-height: 1.65;
}
.site-apps__open {
  margin-top: var(--wds-space-4);
  font-family: var(--wds-font-mono);
  font-size: var(--wds-text-caption);
  letter-spacing: var(--wds-tracking-wide);
  color: var(--wds-accent);
}
@media (max-width: 1023px) {
  .site-apps { grid-template-columns: repeat(2, 1fr); }
}
@media (max-width: 719px) {
  .site-apps { grid-template-columns: 1fr; gap: var(--wds-space-6); }
}
@media (prefers-reduced-motion: reduce) {
  .site-apps__card { transition: none; }
}
"""
